name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
  workflow_dispatch:  # 通过手动触发启动工作流程
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Configure Git
        run: |
          git config --global user.email "zhangpeng19960211@gmail.com"
          git config --global user.name "zephyr-coding"
      - name: Update Submodule
        run: |
          git submodule update --remote --merge
          if [[ $(git status --porcelain) ]]; then
            git pull  # 拉取主项目的最新更改
            git commit -am "Update submodule" && git push
          fi
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      # url: ${{ steps.deployment.outputs.page_url }}
      url: cs-knowledge-tree
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2